// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnfwaamqychulmbjughe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpuZndhYW1xeWNodWxtYmp1Z2hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODE0MzIsImV4cCI6MjA2NjM1NzQzMn0.ZMHX7nRudIx3TJJ83KyOOpNffDRml8UG_iiUNNtpM6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);